// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_in_a_party = "CgkIsubGlZcKEAIQAA"; // <GPGSID>
        public const string achievement_squeezability_is_cool = "CgkIsubGlZcKEAIQAQ"; // <GPGSID>
        public const string achievement_ha_what_a_loving_man = "CgkIsubGlZcKEAIQAg"; // <GPGSID>
        public const string achievement_the_difficulty_is_not_terrible = "CgkIsubGlZcKEAIQBg"; // <GPGSID>
        public const string achievement_hey_youre_in_the_top = "CgkIsubGlZcKEAIQBA"; // <GPGSID>
        public const string achievement_ready_for_battle = "CgkIsubGlZcKEAIQCg"; // <GPGSID>
        public const string achievement_top_1_in_the_world = "CgkIsubGlZcKEAIQCA"; // <GPGSID>
        public const string achievement_thirst_for_speed = "CgkIsubGlZcKEAIQBQ"; // <GPGSID>
        public const string achievement_you_have_so_little_to_do = "CgkIsubGlZcKEAIQAw"; // <GPGSID>
        public const string achievement_fierce_hardcore = "CgkIsubGlZcKEAIQBw"; // <GPGSID>

}

