using UnityEngine;

public class Translate : MonoBehaviour
{
    internal static string[] NameDifficulyRU =
{
        "Cлишком простая",
        "Очень простая",
        "Простая",
        "Слишком маленькая",
        "Очень маленькая",
        "Маленькая",
        "Слишком лёгкая",
        "Очень лёгкая",
        "Лёгкая",
        "Средняя",
        "Высокая",
        "Очень высокая",
        "Лечебная",
        "Агрессивная",
        "Безумная",
        "Принудительно страшная",
        "Страшная",
        "Очень страшная",
        "Невозможная",
        "Очень невозможная"
};

internal static string[] NameDifficulyEng = 
{
        "Too Simple", 
        "Very Simple", 
        "Simple", 
        "Too Small", 
        "Very Small", 
        "Small", 
        "Too Easy", 
        "Very Easy", 
        "Easy", 
        "Medium", 
        "High", 
        "Very High", 
        "Remedial", 
        "Aggressive", 
        "Insane - o", 
        "Force Hard", 
        "Hard", 
        "Very Hard", 
        "Impossible", 
        "Very Impossible" 
};
    internal static string[] NameDifficulyFrench =
{
       "Trop Simple",
        "Très Simple",
        "Simple",
        "Trop Petit",
        "Très Petite",
        "Petit",
        "Trop Facile",
        "Très Facile",
        "Facile",
        "Moyen",
        "Haut",
        "Très Élevé",
        "De rattrapage",
        "Agressif",
        "Insane-o",
        "Force Fort",
        "Dur",
        "Très Dur",
        "Impossible",
        "Très Impossible"
};
    internal static string[] NameDifficulyItalian =
{
        "Troppo Semplice",
        "Molto Semplice",
        "Semplice",
        "Troppo Piccolo",
        "Molto Piccolo",
        "Piccolo",
        "Troppo Facile",
        "Molto Facile",
        "Easy",
        "Medio",
        "Alto",
        "Molto Alto",
        "Correttivo",
        "Aggressivo",
        "Folle-o",
        "Forza Forte",
        "Duro",
        "Molto Difficile",
        "Impossibile",
        "Molto Impossibile"
};
    internal static string[] NameDifficulyGerman =
{
        "Zu Einfach",
        "Sehr Einfach",
        "Einfach",
        "Zu Klein",
        "Sehr Klein",
        "Klein",
        "Zu Einfach",
        "Sehr Einfach",
        "Einfach",
        "Medium",
        "Hoch",
        "Sehr Hoch",
        "Abhilfemaßnahmen",
        "Aggressiv",
        "Insane - o",
        "Kraft Hart",
        "Hart",
        "Sehr Hart",
        "Unmöglich",
        "Sehr Unmöglich"
};
    internal static string[] NameDifficulySpanishSpain =
{
       "Demasiado Simple",
        "Muy Simple",
        "Simple",
        "Demasiado pequeño",
        "Muy pequeño",
        "Pequeño",
        "Demasiado fácil",
        "Muy fácil",
        "Sencillo",
        "Medio",
        "Alto",
        "Muy alto",
        "Remedio",
        "Agresivo",
        "Loco - o",
        "Fuerza dura",
        "Duro",
        "arduamente",
        "Imposible",
        "Muy imposible"
};
    internal static string[] NameDifficulyChina =
{
     "太简单了",
    "很简单",
    "简单",
    "太小",
    "非常小",
    "小",
    "太容易了",
    "很容易",
    "简单",
    "中",
    "高",
    "非常高",
    "补救措施",
    "侵略性",
    "疯狂-o",
    "力硬",
    "硬",
    "很难",
    "不可能",
    "非常不可能"
};
    internal static string[] NameDifficulyDanish =
{
        "For Simpelt",
        "Meget Enkelt",
        "Simpel",
        "For Lille",
        "Meget Lille",
        "Små",
        "For Let",
        "Meget Let",
        "Let",
        "Medium",
        "Høj",
        "Meget Høj",
        "Afhjælpende",
        "Aggressiv",
        "Sindssyg-o",
        "Kraft Hårdt",
        "Hård",
        "Meget Hård",
        "Umulig",
        "Meget Umuligt"
};
    internal static string[] NameDifficulyFinnish =
{
        "Liian Yksinkertaista",
        "Hyvin Yksinkertaista.",
        "Yksinkertainen",
        "Liian Pieni",
        "Hyvin Pieni",
        "Pieni",
        "Liian Helppoa",
        "Hyvin Helppoa",
        "Helppo",
        "Keskikokoinen",
        "Korkea",
        "Hyvin Korkea",
        "Tukiopetus",
        "Aggressiivinen",
        "Mielenvikainen - O",
        "Pakota Kovaa",
        "Kiintolevy",
        "Hyvin Vaikeaa",
        "Mahdoton",
        "Hyvin Mahdotonta."
};
    internal static string[] NameDifficulyNorwegian =
{
        "For Enkel",
        "Svært Enkel",
        "Enkel",
        "For Lite",
        "Veldig Liten",
        "Liten",
        "For Lett",
        "Veldig Lett",
        "Enkel",
        "Medium",
        "Høy",
        "Svært Høy",
        "Avhjelpende",
        "Aggressiv",
        "Sinnsyk - o",
        "Force Hardt",
        "Harddisk",
        "Veldig Hardt",
        "Umulig",
        "Veldig Umulig"
};
    internal static string[] NameDifficulyDutch =
    {
        "Te Simpel",
        "Heel Eenvoudig",
        "Eenvoudig",
        "Te Klein",
        "Zeer Klein",
        "Klein",
        "Te Gemakkelijk",
        "Zeer Gemakkelijk",
        "Gemakkelijk",
        "Medium",
        "Hoge",
        "Zeer Hoog",
        "Corrigerend",
        "Agressief",
        "Krankzinnig-o",
        "Forceer Hard",
        "Hard",
        "Heel Hard",
        "Onmogelijk",
        "Zeer Onmogelijk"
    };
    internal static string[] NameDifficulyPortuguese =
{
        "Demasiado Simples",
        "simples",
        "Simples",
        "pequeno",
        "pequeno",
        "Pequeno",
        "Demasiado Fácil",
        "facil",
        "Facil",
        "Media",
        "Alta",
        "alta",
        "Correctivo",
        "Agressivo",
        "Insano-o",
        "Força Forte",
        "Rigido",
        "muito",
        "Impossivel",
        "Muito Impossível"
};
    internal static string[] NameDifficulySwedish =
{
        "För Enkelt",
        "Mycket Enkelt",
        "Enkel",
        "För Liten",
        "Mycket Liten",
        "Liten",
        "För Lätt",
        "Mycket Lätt",
        "Lätt",
        "Medium",
        "Hög",
        "Mycket Hög",
        "Avhjälpande",
        "Aggressivt",
        "Galen-o",
        "Tvinga Hårt",
        "Hård",
        "Mycket Hårt",
        "Omöjlig",
        "Mycket Omöjligt"
};

internal static string[] NameTextsRU =
{
    "Таблица лидеров",
    "Позиция",
    "Выжимаемость",
    "Никнейм",
    "Загружаем...",
    "Выберите режим игры",
    "Выживание",
    "BlueShift",
    "Соревновательный",
    "Прокачка",
    "Уменьшение спавна бомб во время игры",
    "Прогресс",
    "Увеличение шанса спавна магнитных карт во время игры",
    "Увеличение спавна денег во время игры",
    "Прокачать за:",
    "Твой текущий баланс:",
    "Твой инвентарь",
    "Выберите музыку под которую будете начинать играть",
    "Вы также можете выбрать собственную музыку:",
    "В соревновательном режиме запрещено играть со своими композициями!",
    "Счёт: ",
    "Деньги: ",
    "Комбо ",
    " раз подряд",
    "Сложность: ",
    "Выжито ",
    " песен подряд!",
    "Результат игры",
    "Твоё место в рейтинге:",
    "Общая выжимаемость:",
    "Песен пережито:",
    "До какой сложности достигнуто:",
    "Очков отыграно:",
    "Денег поднято:",
    "Максимальное комбо за игру:",
    "Награды",
    "Пауза:",
    "Убрать рекламу",
    "Вы проиграли уже 3 раза подряд, однако, вы можете навсегда избавиться от рекламы, поддержав разработчика и в добавок к этому получить эту замечательную награду:",
    "Введите своё имя",
    "Выбрать собственную музыку",
    "Сейчас играет: ",
    "Приложение на паузе выходим...",
    "Ошибка подключения к интернету! Пожалуйста подключите ваше андроид устройство к интернету, а затем перезапустите игру...",
    "Подготовка игры к запуску...",
    "Подключение к серверам K.J.P Games...",
    "Обнаружена попытка взлома активация защиты...",
    "Полностью прокачено!",
    "Загрузка ресурсов...",
    "Обновление",
    "Доступно обновление, чтобы продолжить играть установите его!",
    "Обновить",
    "Купить патроны для AWP",
    "Изменить настройки прицеливания",
    "Всего патрон: ",
    "Настройки прицела",
    "Толщина:",
    "Дистанция от центра:",
    "Обводка:",
    "Красный цвет:",
    "Синий цвет:",
    "Зелёный цвет:",
    "Т-орбазный",
    "Способности:",
    "Патроны: ",
    "Название: ",
    "Автор: ",
    "Мастерская",
    "Добавить свою работу в мастерскую",
    "Скины для AWP",
    "Предпросмотр",
    "Музыка",
    "Задний фон",
    "Скин на AWP",
    "Добавление собственной работы в мастерскую",
    "Выберите категорию добавления дополнения:",
    "Выберите файл для загрузки в мастерскую:",
    "Выберите файл иконки для отображения вашей работы в мастерской",
    "Введите название вашей работы",
    "Выбрать файл на устройстве",
    "Введите название вашей работы",
    "Загрузка",
    " из ",
    "Скорость: ",
    "Загрузка завершена",
    "Подсказка: Прожимай карты до конца, чтобы получить дополнительную попытку",
    "Подсказка: Прожимай карты до конца, чтобы получить дополнительное время",
    "Подсказка: Используй магнитные карты, чтобы прожимать несколько карт сразу!",
    "Подсказка: Не промахнись, не прожимай карты с бомбами, иначе рискуешь потерять время!",
    "Подсказка: Не промахнись, не прожимай карты с бомбами, иначе рискуешь потерять попытку!",
    "Обычная музыка:",
    "Музыка из мастерской:",
    "Вау! Посмотри на мой рекорд!,а ты так сможешь? Скачивай игру Classic: https://play.google.com/store/apps/details?id=com.KJPGames.Classic И попробуй обойти меня! Знаю у тебя не выйдет, но попытайся пупсик:)",
    "Удвоить деньги x2?",
    "День",
    "денег",
    "Получено",
    "Ежедневный бонус",
    "Забрать подарок",
    "Проиграш ,но у тебя ещё есть шанс!",
    "Дать шанс",
    "Ежедневный бонус уже ждёт тебя!",
    "Пришло время сыграть по новому, заходи мы соскучились по тебе!",
};
    internal static string[] NameTextsEng =
{
   "Leaderboard",
    "Position",
    "Squeezability",
    "Nickname",
    "Loading...",
    "Select game mode",
    "Survival",
    "BlueShift",
    "Competitive",
    "Pumping",
    "Reducing the spawn of bombs during the game",
    "Progress",
    "Increasing the chance to spawn magnetic cards during the game",
    "Increasing the spawn of money during the game",
    "Pump for:",
    "Your current balance:",
    "Your inventory",
    "Select the music you want to start playing",
    "You can also choose your own music:",
    "It is forbidden to play with your own compositions in competition mode!",
    "Account:",
    "Money:",
    "Combo ",
    "once in a row",
    "Difficulty:",
    "Survived ",
    "songs in a row!",
    "Game result",
    "Your place in the ranking:",
    "Total squeezability:",
    "Songs experienced:",
    "To what degree of complexity is achieved:",
    "Points won:",
    "Money raised:",
    "Maximum combo per game:",
    "Awards",
    "Pause:",
    "Remove ads",
    "You have already lost 3 times in a row, however, you can get rid of advertising forever by supporting the developer and in addition to this get this wonderful award:",
    "Enter your name",
    "You can choose your own music",
    "Now play: ",
    "The app is paused leaving...",
    "Internet connection error! Please connect your Android device to the Internet and then restart the game...",
    "Preparing the game for launch...",
    "Connecting to the servers of K.J.P Games...",
    "Security activation detected a hacking attempt...",
    "Fully upgraded!",
    "Download of resources...",
    "Update",
    "An update is available to continue playing install it!",
    "Update",
    "Buy cartridges for AWP",
    "Change aiming settings",
    "Total cartridge:",
    "Sight settings",
    "Thickness:",
    "Distance from the center:",
    "Outline:",
    "Red:",
    "Blue color:",
    "Green:",
    "T-orbasny",
    "Abilities:",
    "Cartridges: ",
    "Name:",
    "Author:",
    "Workshop",
    "Add your work to the workshop",
    "Skins for AWP",
    "Preview",
    "Music",
    "Background",
    "Skin on AWP",
    "Adding your own work to the workshop",
    "Select the category for adding an extension:",
    "Select a file to upload to the workshop:",
    "Select an icon file to display your work in the workshop",
    "Enter the name of your work",
    "Select a file on your device",
    "Enter the name of your work",
    "Loading",
    " from ",
    "Speed: ",
    "The download is complete",
    "Hint: Squeeze the cards to the end to get an extra try",
    "Hint: Press the cards to the end to get extra time",
    "Hint: Use magnetic cards to squeeze multiple cards at once!",
    "Hint: Do not miss, do not squeeze the cards with bombs, otherwise you risk losing time!",
    "Hint: Do not miss, do not squeeze the cards with bombs, otherwise you risk losing the attempt!",
    "Regular music:",
    "Music from the workshop:",
    "Wow! Look at my record!, can you do that? Download the Classic game: https://play.google.com/store/apps/details?id=com.KJPGames.Classic And try to get around me! I know you can't do it, but try it, baby:)",
    "Double the money x2?",
    "Day",
    "money",
    "Received",
    "Daily bonus",
    "Pick up a gift",
    "Losing ,but you still have a chance!",
    "Give it a chance",
    "The daily bonus is waiting for you!",
    "It's time to play a new game, come on we missed you!",
};
    internal static string[] NameTextsFrench =
{
    "Classement",
    "Position",
    "Survive",
    "Pseudo",
    "Téléchargeant...",
    "Choisissez le mode de jeu",
    "Survie",
    "BlueShift",
    "Compétitif",
    "Purge",
    "Réduction des bombes spawn pendant le jeu",
    "Progrès",
    "Augmenter la chance de spawn des cartes magnétiques pendant le jeu",
    "Augmenter l'argent spawn pendant le jeu",
    "Pomper pour:",
    "Votre solde actuel:",
    "Votre inventaire",
    "Choisissez la musique sous laquelle vous allez commencer à jouer",
    "Vous pouvez également choisir votre propre musique:",
    "En mode compétition, il est interdit de jouer avec vos compositions!",
    "Compte: ",
    "Argent: ",
    "Combo ",
    "une fois de suite",
    "Complexité: ",
    "Survive ",
    "des chansons d'affilée!",
    "Résultat du jeu",
    "Ta place dans le classement:",
    "Capacité de compression totale:",
    "Chansons vécues:",
    "Jusqu'à quelle complexité est atteint:",
    "Points joués:",
    "L'argent levé:",
    "Combo maximum par match:",
    "Récompenses",
    "Pause:",
    "Supprimer la publicité",
    "Vous avez déjà perdu 3 fois de suite, cependant, vous pouvez vous débarrasser de la publicité pour toujours, en soutenant le développeur et en plus de cela, obtenir cette merveilleuse récompense:",
    "Entrez votre nom",
    "Choisissez votre propre musique",
    "Joue maintenant: ",
    "L'application est en pause...",
    "Erreur de connexion Internet! Veuillez connecter votre appareil Android à Internet, puis redémarrez le jeu...",
    "Préparation du jeu pour le lancement...",
    "Se connecter aux serveurs K.J.P Games...",
    "Une tentative de piratage a été détectée...",
    "Complètement pompé!",
    "Chargement des ressources...",
    "Mise à jour",
    "Mise à jour disponible pour continuer à jouer installez-le!",
    "Actualiser",
    "Acheter des cartouches pour AWP",
    "Modifier les paramètres de visée",
    "Cartouche totale: ",
    "Paramètres de visée",
    "Épaisseur:",
    "Distance du centre:",
    "Contour:",
    "Rouge:",
    "Bleu:",
    "Vert:",
    "T-orbaz",
    "Possibilité:",
    "Cartouches: ",
    "Nom: ",
    "Auteur: ",
    "Atelier",
    "Ajouter votre travail à l'atelier",
    "Skins pour AWP",
    "Aperçu",
    "Musique",
    "L'arrière-plan",
    "Skin on AWP",
    "Ajouter votre propre travail à l'atelier",
    "Choisissez une catégorie d'Add-on:",
    "Sélectionnez le fichier à télécharger dans l'atelier:",
    "Choisissez un fichier d'icônes pour afficher votre travail dans l'atelier",
    "Entrez le titre de votre travail",
    "Sélectionner un fichier sur l'appareil",
    "Entrez le titre de votre travail",
    "Téléchargement",
    " de ",
    "Vitesse: ",
    "Téléchargement terminé",
    "Astuce: Serrez les cartes jusqu'à la fin pour obtenir un essai supplémentaire",
    "Astuce: Serrez les cartes jusqu'à la fin pour obtenir plus de temps",
    "Astuce: Utilisez des cartes magnétiques pour presser plusieurs cartes à la fois!",
    "Astuce: ne manquez pas, ne pas brûler les cartes avec des bombes, sinon vous risquez de perdre du temps!",
    "Astuce: ne manquez pas, ne pas brûler les cartes avec des bombes, sinon vous risquez de perdre la tentative!",
    "Musique ordinaire:",
    "Musique de l'atelier:",
    "Wow! Regarde mon record!. et tu peux faire ça? Téléchargez Classic: https://play.google.com/store/apps/details?id=com.KJPGames.Classic et essayez de me contourner! Je sais que tu ne peux pas le faire, mais essaie de le faire.:)",
    "Doubler l'argent x2?",
    "Jour",
    "argents",
    "Reçu",
    "Bonus quotidien",
    "Ramasser un cadeau",
    "Perdre, mais vous avez encore une chance!",
    "Donner une chance",
    "Le bonus quotidien vous attend déjà!",
    "Il est temps de jouer à nouveau, venez nous avons manqué!",
};
    internal static string[] NameTextsItalian =
{
    "Classifica",
    "Posizione",
    "Compressione",
    "Nickname",
    "Caricante...",
    "Scegli la modalità di gioco",
    "Sopravvivenza",
    "BlueShift",
    "Competitivo",
    "Pompaggio",
    "Ridurre le bombe durante il gioco",
    "Progresso",
    "Aumentare la probabilità di carte magnetiche spawn durante il gioco",
    "Aumentare la quantità di denaro durante il gioco",
    "Pompare per:",
    "Il tuo saldo attuale:",
    "Il tuo inventario",
    "Scegli la musica per cui inizierai a suonare",
    "Puoi anche scegliere la tua musica:",
    "In modalità competitiva è vietato giocare con i tuoi brani!",
    "Conto: ",
    "Soldi: ",
    "Combo ",
    "una volta di fila",
    "Complessità: ",
    "Sopravvissuto ",
    "canzoni di fila!",
    "Risultato del gioco",
    "Il tuo posto nella classifica:",
    "Compressione totale:",
    "Canzoni vissute:",
    "Fino a che difficoltà è stato raggiunto:",
    "Punti giocati:",
    "Denaro sollevato:",
    "Combo massimo per partita:",
    "Premi",
    "Pausa:",
    "Rimuovere gli annunci",
    "Hai già perso 3 volte di fila, tuttavia, puoi eliminare definitivamente gli annunci supportando lo sviluppatore e in aggiunta a ciò ottieni questo meraviglioso premio:",
    "Inserisci il tuo nome",
    "Scegli la tua musica",
    "Ora Gioca: ",
    "L'app è in pausa...",
    "Errore di connessione a Internet! Si prega di collegare il dispositivo Android a Internet e quindi riavviare il gioco...",
    "Preparare il gioco per il lancio...",
    "Connessione ai server di K.J.P Games...",
    "Rilevato tentativo di manomissione attivazione della protezione...",
    "Completamente pompato!",
    "Caricamento delle risorse...",
    "Aggiornamento",
    "Aggiornamento disponibile per continuare a giocare installarlo!",
    "Aggiornare",
    "Acquista munizioni per AWP",
    "Modificare le impostazioni di puntamento",
    "Totale cartuccia: ",
    "Impostazioni del mirino",
    "Spessore:",
    "Distanza dal centro:",
    "Dribbling:",
    "Rosso:",
    "Blu:",
    "Verde:",
    "T-orbase",
    "Capacità:",
    "Cartucce: ",
    "Titolo: ",
    "Autore: ",
    "Officina",
    "Aggiungi il tuo lavoro al laboratorio",
    "Pelli per AWP",
    "Anteprima",
    "Musica",
    "Sfondo",
    "Skin su AWP",
    "Aggiungere il proprio lavoro al laboratorio",
    "Seleziona la categoria di aggiunta del componente aggiuntivo:",
    "Selezionare il file da caricare nell'officina:",
    "Selezionare le icone di file per visualizzare il vostro lavoro in officina",
    "Inserisci il titolo del tuo lavoro",
    "Seleziona un file sul dispositivo",
    "Inserisci il titolo del tuo lavoro",
    "Caricamento",
    " di ",
    "Velocità: ",
    "Download completato",
    "Suggerimento: premi le carte fino alla fine per ottenere un ulteriore tentativo",
    "Suggerimento: premi le carte fino alla fine per guadagnare tempo extra",
    "Suggerimento: usa le carte magnetiche per accumulare più carte contemporaneamente!",
    "Suggerimento: non perdere, non vivere le carte con le bombe, altrimenti si rischia di perdere tempo!",
    "Suggerimento: non perdere, non perdere le carte con le bombe, altrimenti rischi di perdere il tentativo!",
    "MUSICA NORMALE:",
    "Musica dal laboratorio:",
    "WOW! Guarda il mio record!. puoi farlo? Scarica il gioco Classic: https://play.google.com/store/apps/details?id=com.KJPGames.Classic e cercare di aggirare me! So che non ce la farai, ma provaci, tesoro.:)",
    "Raddoppiare i soldi x2?",
    "Giorno",
    "soldi",
    "Ricevuto",
    "Bonus giornaliero",
    "Prendi un regalo",
    "Perdere, ma hai ancora una possibilità!",
    "Dare una possibilità",
    "Il bonus giornaliero ti sta aspettando!",
    "E' tempo di giocare un nuovo gioco, vieni ci sei mancato!",
};
    internal static string[] NameTextsGerman =
{
    "Rangliste",
    "Position",
    "Squeeze-out",
    "Nickname",
    "Geladener...",
    "Wählen Sie den Spielmodus",
    "Überleben",
    "BlueShift",
    "Wettbewerbsfähig",
    "Pumpen",
    "Verringerung der Spawn-Bomben während des Spiels",
    "Fortschritt",
    "Erhöhung der Chance Spawn Magnetkarten während des Spiels",
    "Erhöhung der Spawn Geld während des Spiels",
    "Pumpen für:",
    "Ihre aktuelle Bilanz:",
    "Dein Inventar",
    "Wählen Sie die Musik, unter der Sie anfangen zu spielen",
    "Sie können auch Ihre eigene Musik auswählen:",
    "Im Wettbewerbsmodus ist es verboten, mit Ihren Songs zu spielen!",
    "Konto: ",
    "Geld: ",
    "Combo ",
    "einmal hintereinander",
    "Komplexität: ",
    "Überlebt ",
    "Songs in einer Reihe!",
    "Das Ergebnis des Spiels",
    "Dein Platz in der Rangliste:",
    "Insgesamt Squeeze:",
    "Lieder erlebt:",
    "Bis zu welcher Komplexität wird erreicht:",
    "Punkte gewonnen:",
    "Geld angehoben:",
    "Maximale Combo pro Spiel:",
    "Auszeichnungen",
    "Pause:",
    "Anzeigen entfernen",
    "Sie haben bereits 3 mal in Folge verloren, aber Sie können die Werbung dauerhaft loswerden, indem Sie den Entwickler unterstützen und zusätzlich diese wunderbare Belohnung erhalten:",
    "Geben Sie Ihren Namen ein",
    "Wählen Sie Ihre eigene Musik",
    "Jetzt spielt: ",
    "Die App ist auf Pause verlassen...",
    "Internet-Verbindung fehlgeschlagen! Bitte verbinden Sie Ihr Android-Gerät mit dem Internet und starten Sie das Spiel neu...",
    "Bereiten Sie das Spiel zu starten...",
    "Verbindung zu K.J.P Games-Servern...",
    "Ein Einbruchsversuch wurde festgestellt...",
    "Komplett gepumpt!",
    "Ressourcen laden...",
    "Aggiornamento",
    "Aggiornamento disponibile per continuare a giocare installarlo!",
    "Aggiornare",
    "Aggiornamenti di notizie",
    "Kaufen Sie Patronen für AWP",
    "Zieleinstellungen ändern",
    "Insgesamt Patrone: ",
    "Zielfernrohr-Einstellungen",
    "Stärke:",
    "Entfernung vom Zentrum:",
    "Scheren:",
    "Rote:",
    "Blau:",
    "Grün:",
    "T-orbazny",
    "Fähigkeit:",
    "Patrons: ",
    "Name: ",
    "Autor: ",
    "Werkstatt",
    "Fügen Sie Ihre Arbeit der Werkstatt hinzu",
    "Skins für AWP",
    "Vorschau",
    "Musik",
    "Hintergrund hintergrund",
    "Skin auf AWP",
    "Eigene Arbeit zur Werkstatt hinzufügen",
    "Wählen Sie die Kategorie add-ons:",
    "Wählen Sie die Datei aus, die Sie in die Werkstatt hochladen möchten:",
    "Wählen Sie eine Icon-Datei, um Ihre Arbeit in der Werkstatt anzuzeigen",
    "Geben Sie den Namen Ihrer Arbeit ein",
    "Datei auf dem Gerät auswählen",
    "Geben Sie den Namen Ihrer Arbeit ein",
    "Laden",
    " aus ",
    "Geschwindigkeit: ",
    "Download abgeschlossen",
    "Tipp: bleib die Karten bis zum Ende, um einen zusätzlichen Versuch zu bekommen",
    "Tipp: Bleib die Karten bis zum Ende, um zusätzliche Zeit zu erhalten",
    "Tipp: verwenden Sie Magnetkarten, um mehrere Karten auf einmal zu speichern!",
    "Tipp: verpassen Sie nicht, nicht die Karten mit Bomben zu Leben, sonst riskieren Sie, Zeit zu verlieren!",
    "Tipp: nicht verpassen, nicht die Karten mit den Bomben zu Leben, sonst riskierst du den Versuch zu verlieren!",
    "Normale Musik:",
    "Musik aus der Werkstatt:",
    "Wow! Schau dir meinen Rekord an!- kannst du das? Laden Sie das Spiel Classic: https://play.google.com/store/apps/details?id=com.KJPGames.Classic und versuchen, mich zu umgehen! Ich weiß, du wirst es nicht schaffen, aber Versuch es mit einem Pupsik:)",
    "Verdoppeln Sie das Geld x2?",
    "Tag",
    "Gelder",
    "Eingegangen",
    "Täglicher Bonus",
    "Ein Geschenk abholen",
    "Verlieren ,aber du hast noch eine Chance!",
    "Eine Chance geben",
    "Der tägliche Bonus wartet schon auf dich!",
    "Es ist Zeit, ein neues Spiel zu spielen, komm rein wir haben dich vermisst!",
};
    internal static string[] NameTextsSpanishSpain =
{
    "Tabla de clasificación",
    "Posición",
    "Exprimir",
    "Nickname",
    "Cargado...",
    "Seleccione el modo de juego",
    "Supervivencia",
    "BlueShift",
    "Competitivo",
    "Bombeo",
    "Reducción de las bombas de desove durante el juego",
    "Progreso",
    "Aumentar la posibilidad de generar tarjetas magnéticas durante el juego",
    "Aumentar el desove de dinero durante el juego",
    "Bombear para:",
    "Tu saldo actual:",
    "Tu inventario",
    "Seleccione la música que va a empezar a jugar",
    "También puedes elegir tu propia música:",
    "En el modo competitivo, ¡está Prohibido jugar con sus composiciones!",
    "Factura: ",
    "Dinero: ",
    "Combo ",
    "una vez en una fila",
    "Complejidad: ",
    "Sobrevive ",
    "¡Canciones seguidas!",
    "Resultado del juego",
    "Tu lugar en el ranking:",
    "Exprimidor total:",
    "Canciones vividas:",
    "Hasta qué punto se ha logrado la complejidad:",
    "Puntos jugados:",
    "Dinero recaudado:",
    "Máximo Combo por juego:",
    "Premios",
    "Pausa:",
    "Eliminar anuncios",
    "Ya has perdido 3 veces seguidas, sin embargo, puedes deshacerte de los anuncios para siempre, apoyando al desarrollador y, además, obtener esta maravillosa recompensa:",
    "Escriba su nombre",
    "Elige tu propia música",
    "Ahora juega: ",
    "La aplicación está en pausa...",
    "Error de conexión a Internet! Por favor, conecte su dispositivo Android a Internet y luego reinicie el juego...",
    "Preparación del juego para el lanzamiento...",
    "Conexión a los servidores de K.J.P Games...",
    "Se ha detectado un intento de hackeo activando la protección...",
    "¡Completamente bombeado!",
    "Carga de recursos...",
    "Actualización",
    "Actualización disponible para seguir jugando ¡instálalo!",
    "Renovar",
    "Actualizaciones de noticias",
    "Comprar munición para AWP",
    "Cambiar la configuración de puntería",
    "Cartucho total: ",
    "Ajustes de vista",
    "Espesor:",
    "Distancia desde el centro:",
    "Dribling:",
    "Rojo:",
    "Azul:",
    "Verde:",
    "T-orbaz",
    "Capacidades:",
    "Cartuchos: ",
    "Nombre: ",
    "Autor: ",
    "Taller",
    "Añadir su trabajo al taller",
    "Skins para AWP",
    "Vista previa",
    "Músico",
    "Fondo",
    "Piel en AWP",
    "Agregando su propio trabajo al taller",
    "Seleccione la categoría agregar complemento:",
    "Seleccione el archivo que desea cargar en el taller:",
    "Seleccione el archivo de iconos para Mostrar su trabajo en el taller",
    "Ingrese el nombre de su trabajo",
    "Seleccionar archivo en el dispositivo",
    "Ingrese el nombre de su trabajo",
    "Carga",
    " de ",
    "Velocidad: ",
    "Descarga completa",
    "Sugerencia: Traza las cartas hasta el final para obtener un intento adicional",
    "Sugerencia: Exprime las cartas hasta el final para obtener tiempo extra",
    "Sugerencia: ¡Usa tarjetas magnéticas para exprimir varias cartas a la vez!",
    "Sugerencia: ¡No te pierdas, no gastes cartas con bombas, o te arriesgas a perder el tiempo!",
    "Sugerencia: ¡No te pierdas, no gastes cartas con bombas, o te arriesgas a perder el intento!",
    "Música ordinaria:",
    "Música del taller:",
    "Wow! ¡Mira mi récord!y tú puedes? Descarga el juego Classic: https://play.google.com/store/apps/details?id=com.KJPGames.Classic ¡y trata de superarme! Sé que no vas a funcionar, pero prueba el muñeco.:)",
    "¿Duplicar el dinero?",
    "Día",
    "dineros",
    "Recibí",
    "Bono diario",
    "Recoger el regalo",
    "Perder, pero todavía tienes una oportunidad!",
    "Dar una oportunidad",
    "¡El bono diario ya te está esperando!",
    "Es hora de jugar de nuevo, ven, ¡te extrañamos!",
};
    internal static string[] NameTextsChina =
{
    "排行榜",
    "位置",
    "挤压性",
    "昵称",
    "加载。..",
    "选择游戏模式",
    "生存",
    "蓝移",
    "竞争",
    "抽水",
    "在游戏过程中减少炸弹的产卵",
    "进展",
    "增加在游戏过程中产生磁卡的机会",
    "在游戏过程中增加金钱的产卵",
    "泵:",
    "您当前的余额:",
    "您的库存",
    "选择要开始播放的音乐",
    "你也可以选择自己的音乐:",
    "禁止在比赛模式下玩自己的作品！",
    "账户:",
    "钱:",
    "组合 ",
    "连续一次",
    "困难:",
    "幸存下来 ",
    "连续的歌曲！",
    "游戏结果",
    "你在排名中的位置:",
    "总挤压性:",
    "歌曲经历:",
    "达到什么程度的复杂性:",
    "赢得积分:",
    "募集资金:",
    "每场比赛的最大组合:",
    "奖项",
    "暂停:",
    "删除广告",
    "你已经连续失去了3次，但是，你可以通过支持开发商永远摆脱广告，除了这个获得这个美好的奖项:",
    "输入您的姓名",
    "你可以选择自己的音乐",
    "现在玩: ",
    "该应用程序暂停退出...",
    "互联网连接错误！ 请将您的Android设备连接到互联网，然后重新启动游戏...",
    "准备游戏发射...",
    "连接到K.J.P游戏的服务器...",
    "安全激活检测到黑客攻击。..",
    "全面升级！",
    "资源下载...",
    "更新",
    "更新可以继续播放安装它！",
    "更新",
    "购买AWP墨盒",
    "更改瞄准设置",
    "总墨盒:",
    "视线设置",
    "厚度:",
    "距离中心:",
    "大纲:",
    "红:",
    "蓝色:",
    "绿色:",
    "T",
    "能力:",
    "墨盒: ",
    "名称:",
    "作者:",
    "讲习班",
    "将您的作品添加到车间",
    "Awp的皮肤",
    "预览",
    "音乐",
    "背景",
    "AWP上的皮肤",
    "将自己的作品添加到车间",
    "选择添加扩展的类别:",
    "选择一个文件上传到车间:",
    "选择一个图标文件以在工作坊中显示您的作品",
    "输入作品的名称",
    "选择设备上的文件",
    "输入作品的名称",
    "加载",
    " 从 ",
    "速度: ",
    "下载完成",
    "提示：挤压卡到最后得到一个额外的尝试",
    "提示：按卡到最后，以获得额外的时间",
    "提示：使用磁卡一次挤压多张卡！",
    "提示：千万不要错过，不要用炸弹挤卡，否则你可能会失去时间！",
    "提示：千万不要错过，不要用炸弹挤卡，否则你可能会失去尝试！",
    "常规音乐:",
    "音乐从车间:",
    "哇！ 看看我的记录！ 你能做到?？ 下载经典游戏：https://play.google.com/store/apps/details?id=com.KJPGames.Classic 并尝试让我身边！ 我知道你做不到，但试试吧，宝贝:)",
    "双倍的钱x2？",
    "日",
    "钱",
    "收到",
    "每日奖金",
    "拿起礼物",
    "失去，但你仍然有机会！",
    "给它一个机会",
    "每日奖金正等着你！",
    "现在是时候玩一个新的游戏，来吧，我们错过了你！",
};
    internal static string[] NameTextsDanish =
{
    "Førertavle",
    "Position",
    "Klemme",
    "Kaldenavn",
    "Lastning...",
    "Vælg spiltilstand",
    "Overlevelse",
    "BlueShift",
    "Konkurrencedygtig",
    "Pumpende",
    "At reducere yngel af bomber under spillet",
    "Fremskridt",
    "Øger chancen for at danne magnetiske kort under spillet",
    "At øge pengenes yngel under spillet",
    "Pump for:",
    "Din nuværende balance:",
    "Lageret",
    "Vælg den musik du vil begynde at spille",
    "Du kan også vælge din egen musik:",
    "Det er forbudt at lege med sine egne kompositioner i konkurrence mode!",
    "Konto:",
    "Penge:",
    "Combo ",
    "en gang i træk",
    "Vanskelighed:",
    "Overleve ",
    "sange i træk !",
    "Spilresultat",
    "Din plads i rangeringen:",
    "Total klemme:",
    "Erfarne sange:",
    "I hvilken grad af kompleksitet opnås:",
    "Point vundet:",
    "Tilvejebragte midler:",
    "Maksimal kombination pr spil:",
    "Awards",
    "Pause:",
    "Fjern annoncer",
    "Du har allerede tabt 3 gange i træk, men du kan slippe af med reklamer for evigt ved at støtte bygherren og ud over dette få denne vidunderlige pris:",
    "Indtast dit navn",
    "Du kan vælge din egen musik",
    "Spil nu: ",
    "App ' en holder pause for at komme ud...",
    "Internetforbindelse fejl! Forbind venligst din androide enhed til internettet og genstart spillet...",
    "Gør spillet klar til affyring...",
    "Forbinder til serverne af K.J.P spil...",
    "Sikkerhedsaktiveringen opfangede et hackingsforsøg...",
    "Fuldt opgraderet !",
    "Hent ressourcer...",
    "Opdatering",
    "En opdatering er tilgængelig for at fortsætte afspilningen!",
    "Opdatering",
    "Nyhedsopdateringer",
    "Køb ÅLESPATRONER",
    "Ændr indstillingsindstillinger",
    "Cylinderampul i alt:",
    "Synsindstillinger",
    "Tykkelse:",
    "Afstand til midten:",
    "Skitsere:",
    "Red:",
    "Blå farve:",
    "Grøn:",
    "T",
    "Evne:",
    "Navn:",
    "Forfatter:",
    "Workshop",
    "Tilføj dit arbejde til værkstedet",
    "Skind til ål",
    "Preview",
    "Musik",
    "Baggrund",
    "Hud mod ål",
    "At tilføje dit eget arbejde til værkstedet",
    "Vælg kategorien for tilføjelse af en udvidelse:",
    "Vælg en fil at uploade til værkstedet:",
    "Vælg en ikon-fil til at vise dit arbejde i værkstedet",
    "Indtast navnet på dit arbejde",
    "Vælg en fil på din enhed",
    "Indtast navnet på dit arbejde",
    "Lastning",
    " fra ",
    "Hastighed: ",
    "Blækpatron: ",
    "Hentningen er færdig",
    "Vink: klem kortene til enden for at få et ekstra forsøg",
    "Vink: tryk på kortene for at få ekstra tid",
    "Brug magnetiske kort til at klemme flere kort med det samme !",
    "RAM ikke forbi, klem ikke kortene med bomber, ellers risikerer du at miste tid!",
    "RAM ikke forbi, klem ikke kortene med bomber, ellers risikerer du at miste forsøget !",
    "Almindelig musik:",
    "Musik fra værkstedet:",
    "Hold da op ! Se min straffeattest! kan du gøre det? Hent det klassiske spil: https://play.google.com/store/apps/details?id=com.KJPGames.Classic og prøv at komme udenom mig! Jeg ved, du ikke kan, men prøv det.:)",
    "Dobbelt så mange penge som 2?",
    "Dag",
    "penge",
    "Modtaget",
    "Daglig bonus",
    "Hent en gave",
    "At tabe, men du har stadig en chance!",
    "Giv det en chance",
    "Den daglige bonus venter på dig !",
    "Det er på tide at spille et nyt spil, kom nu vi har savnet dig!",
};
    internal static string[] NameTextsFinnish =
{
    "Leader-taulu",
    "Asema",
    "Puristettavuus",
    "Lempinimi",
    "Lastaus...",
    "Valitse pelitila",
    "Selviytyminen",
    "Bluesift",
    "Kilpailu",
    "Pumppaa",
    "Pommien sikiön vähentäminen pelin aikana",
    "Edistyminen",
    "Lisään mahdollisuutta luoda magneettikortteja pelin aikana",
    "Lisään rahan kutua pelin aikana",
    "Pumppu:",
    "Nykyinen tasapainosi:",
    "Inventaariosi",
    "Valitse musiikki, jota haluat alkaa soittaa",
    "Voit myös valita oman musiikkisi:",
    "On kiellettyä leikkiä omilla sävellyksillään kilpailutilassa!",
    "Tili:",
    "Raha:",
    "Combo ",
    "kerran peräkkäin",
    "Vaikeus:",
    "Hengissä ",
    "lauluja peräkkäin!",
    "Pelin tulos",
    "Paikkasi sijassa:",
    "Täydellinen puristettavuus:",
    "Kokeneet kappaleet:",
    "Missä määrin monimutkaisuus on saavutettu:",
    "Pisteitä voitettu:",
    "Rahaa kerätty:",
    "Maksimi yhdistelmä peliä kohti:",
    "Palkinto",
    "Keskeyttää:",
    "Poista ilmoitukset",
    "Sinulla on jo menettänyt 3 kertaa peräkkäin, voit kuitenkin päästä eroon mainonta ikuisesti tukemalla kehittäjä ja lisäksi saada tämä ihana palkinto:",
    "Anna nimesi",
    "Voit valita oman musiikkisi",
    "Soita: ",
    "Sovellus on pysäytetty...",
    "Internet-yhteysvirhe! Yhdistä Androidilaitteesi Internetiin ja aloita peli uudelleen...",
    "Valmistaudun laukaisuun...",
    "Yhdistän KJP-pelien servereille...",
    "Turvajärjestelmä havaitsi hakkerointiyrityksen...",
    "Täysin päivitetty!",
    "Resurssien lataaminen...",
    "Päivitys",
    "Päivitys on käytettävissä jatkettaessa sen asentamista!",
    "Päivitys",
    "Osta AWP-patruunoita",
    "Muuta kohdistusasetuksia",
    "Sylinteriampulli yhteensä:",
    "Näön asetukset",
    "Paksuudeltaan:",
    "Etäisyys keskeltä:",
    "Hahmotella:",
    "Punainen:",
    "Sininen väri:",
    "Vihreä:",
    "T",
    "Kykyjään:",
    "Värikasetti: ",
    "Nimi:",
    "Tekijä:",
    "Työpaja",
    "Lisää työsi työpajaan",
    "AWP: n nahkoja",
    "Esikatselu",
    "Musiikki",
    "Tausta",
    "Iho AWP: llä",
    "Oman työn lisääminen työpajaan",
    "Valitse laajennuksen lisäämisen kategoria:",
    "Valitse työpajaan siirrettävä tiedosto:",
    "Valitse kuvaketiedosto, joka näyttää työsi korjaamossa",
    "Anna työsi nimi",
    "Valitse tiedosto laitteestasi",
    "Anna työsi nimi",
    "Lastaus",
    " päässä ",
    "Nopeus: ",
    "Lataus on valmis",
    "Vinkki: purista kortit loppuun saadaksesi ylimääräisen yrityksen",
    "Vinkki: paina kortit loppuun saadaksesi lisäaikaa",
    "Vinkki: purista useita kortteja magneettikorteilla kerralla!",
    "Vinkki: älä ammu ohi, älä purista kortteja pommeilla, muuten menetät aikaa!",
    "Vinkki: älä ammu ohi, älä purista kortteja pommeilla, muuten voit menettää yrityksesi!",
    "Tavallista musiikkia:",
    "Musiikkia työpajalta:",
    "Vau! Katso ennätystäni! pystytkö siihen? Lataa klassinen peli: https://play.google.com/store/apps/details?id=com.KJPGames.Classic ja yritä päästä ohitseni! Tiedän, ettet pysty siihen, mutta kokeile sitä, kulta.:)",
    "Tuplaa x2-rahat?",
    "Päivä",
    "raha",
    "Saatu",
    "Päivittäinen bonus",
    "Ota lahja",
    "Häviät, mutta sinulla on vielä mahdollisuus!",
    "Anna sille mahdollisuus",
    "Daily bonus odottaa sinua!",
    "On aika pelata uutta peliä, kaipasimme sinua!",
};
    internal static string[] NameTextsNorwegian =
{
    "Poengtavle",
    "Posisjon",
    "Squeezability",
    "Kallenavn",
    "Lasting...",
    "Velg spillet modus",
    "Overlevelse",
    "BlueShift",
    "Konkurransedyktig",
    "Pumpe",
    "Å redusere gyte av bomber i løpet av spillet",
    "Fremgang",
    "Å øke sjansen for å gyte magnetiske kort i løpet av spillet",
    "Øke gyte av penger i løpet av spillet",
    "Pumpe for:",
    "Din nåværende saldo:",
    "Lagerbeholdningen",
    "Velg musikken du ønsker å begynne å spille",
    "Du kan også velge din egen musikk:",
    "Det er forbudt å spille med dine egne komposisjoner i konkurranse modus!",
    "Konto:",
    "Penger:",
    "Kombinasjon ",
    "en gang i en rad",
    "Vanskelighet:",
    "Overleve ",
    "sanger på rad!",
    "Spillet resultat",
    "Din plass i rangeringen:",
    "Total squeezability:",
    "Sanger erfarne:",
    "I hvilken grad av kompleksitet er oppnådd:",
    "Poeng vunnet:",
    "Penger som er samlet inn:",
    "Maksimal combo per spill:",
    "Pris",
    "Pause:",
    "Fjerne annonser",
    "Du har allerede gått ned 3 ganger på rad, men du kan bli kvitt reklame for alltid ved å støtte utvikleren, og i tillegg til dette får denne fantastiske prisen:",
    "Skriv inn ditt navn",
    "Du kan velge din egen musikk",
    "Spill nå: ",
    "Appen er satt på pause for å avslutte...",
    "Internett-tilkobling feil! Vennligst koble til din Android-enhet til Internett og deretter starte spillet...",
    "Klargjøre spill for start...",
    "Koble til serverne til K.J.P Spill...",
    "Sikkerhet aktivering oppdaget et forsøk på hacking...",
    "Fullt oppgradert!",
    "Nedlasting av ressurser...",
    "Päivitys",
    "Päivitys on käytettävissä jatkettaessa sen asentamista!",
    "Päivitys",
    "Kjøpe blekkpatroner AWP",
    "Endre sikte innstillinger",
    "Totalt kassett:",
    "Syn-innstillinger",
    "Tykkelse:",
    "Avstand fra sentrum:",
    "Omriss:",
    "Rød:",
    "Blått:",
    "Grønn:",
    "T",
    "Evne:",
    "Tonerkassett: ",
    "Navn:",
    "Forfatter:",
    "Verksted",
    "Legg arbeidet til verkstedet",
    "Skins for AWP",
    "Forhåndsvisning",
    "Musikk",
    "Bakgrunn",
    "Huden på AWP",
    "Legge til ditt eget arbeid til verkstedet",
    "Velg kategori for å legge til en utvidelse:",
    "Velg en fil du vil laste opp til verkstedet:",
    "Velg en fil-ikonet for å vise frem ditt arbeide i verkstedet",
    "Skriv inn navnet på arbeidet ditt",
    "Velg en fil på din enhet",
    "Skriv inn navnet på arbeidet ditt",
    "Lasting",
    " fra ",
    "Hastighet: ",
    "Nedlastingen er fullført",
    "Hint: Presse kortene til slutt å få en ekstra prøve",
    "Hint: Trykk kort til slutt å få ekstra tid",
    "Hint: Bruk magnetiske kort til å presse flere kort på en gang!",
    "Hint: ikke gå glipp av, må du ikke presse kortene med bomber, ellers risikerer du å miste tid!",
    "Hint: ikke gå glipp av, må du ikke presse kortene med bomber, ellers risikerer du å miste forsøk!",
    "Vanlig musikk:",
    "Musikk fra verkstedet:",
    "Wow! Se på min rekord! kan du gjøre det? Last ned det Klassiske spillet: https://play.google.com/store/apps/details?id=com.KJPGames.Classic Og prøve å komme seg rundt meg! Jeg vet at du ikke kan gjøre det, men prøv det, baby:)",
    "Doble pengene x2?",
    "Dag",
    "penger",
    "Mottatt",
    "Daglig-bonus",
    "Plukke opp en gave",
    "Å miste ,men du har fortsatt en sjanse!",
    "Gi det en sjanse",
    "Den daglige bonus venter på deg!",
    "Det er på tide å spille et nytt spill, kom vi savnet deg!",
};
    internal static string[] NameTextsDutch =
{
    "Klassement",
    "Positie",
    "Knijpbaarheid",
    "Bijnaam",
    "Laden...",
    "Spelmodus selecteren",
    "Overleving",
    "BlueShift",
    "Concurrerend",
    "Pompen",
    "Het verminderen van het gebroed van bommen tijdens het spel",
    "Vooruitgang",
    "Het vergroten van de kans om magnetische kaarten te paaien tijdens het spel",
    "Het vergroten van het gebroed van geld tijdens het spel",
    "Pomp voor:",
    "Uw huidige balans:",
    "Uw inventaris",
    "Selecteer de muziek die u wilt beginnen te spelen",
    "U kunt ook uw eigen muziek kiezen:",
    "Het is verboden om met uw eigen composities te spelen in concurrentiemodus!",
    "Account:",
    "Geld:",
    "Combo ",
    "eenmaal op rij",
    "Moeilijkheid:",
    "Overleven ",
    "liedjes op een Rij!",
    "Spel resultaat",
    "Uw plaats in de ranking:",
    "Totale knijpbaarheid:",
    "Liedjes ervaren:",
    "In welke mate van complexiteit wordt bereikt:",
    "Punten gewonnen:",
    "Opgenomen geld:",
    "Maximale combo per spel:",
    "Award",
    "Pauzeren:",
    "Advertenties verwijderen",
    "Je hebt al 3 keer op rij verloren, echter, kunt u zich ontdoen van reclame voor altijd door het ondersteunen van de ontwikkelaar en in aanvulling op deze krijgen deze prachtige award:",
    "Voer uw naam in",
    "U kunt uw eigen muziek kiezen",
    "Speel nu: ",
    "De app is gepauzeerd om te stoppen...",
    "Fout in internetverbinding! Sluit uw Android-apparaat aan op het Internet en herstart het spel...",
    "Gør spillet klar til affyring...",
    "Verbinden met de servers van K.J.P Games...",
    "Beveiliging activatie detecteerde een hacking poging...",
    "Volledig opgewaardeerd!",
    "Downloaden van bronnen...",
    "Update",
    "Er is een update beschikbaar om door te gaan met het afspelen van install!",
    "Update",
    "Koop AWP patronen",
    "Richtinstellingen wijzigen",
    "Totaal patroon:",
    "Gezichtsinstellingen",
    "Dikte:",
    "Afstand van het centrum:",
    "Overzicht:",
    "Rode:",
    "Blauwe kleur:",
    "Groen:",
    "T",
    "Mogelijkheid:",
    "Inktcartridges: ",
    "Naam:",
    "Auteur:",
    "Workshop",
    "Voeg uw werk toe aan de workshop",
    "Huiden voor AWP",
    "Preview",
    "Muziek",
    "Achtergrond",
    "Huid op AWP",
    "Uw eigen werk aan de workshop toevoegen",
    "Selecteer de categorie voor het toevoegen van een extensie:",
    "Selecteer een bestand om te uploaden naar de workshop:",
    "Selecteer een pictogrambestand om uw werk in de workshop weer te geven",
    "Voer de naam van uw werk in",
    "Selecteer een bestand op uw apparaat",
    "Voer de naam van uw werk in",
    "Laden",
    " van ",
    "Snelheid: ",
    "De download is voltooid",
    "Hint: knijp de kaarten tot het einde om een extra poging te krijgen",
    "Hint: druk op de kaarten tot het einde om extra tijd te krijgen",
    "Hint: gebruik magnetische kaarten om meerdere kaarten tegelijk uit te drukken!",
    "Hint: niet missen, niet knijpen de kaarten met bommen, anders riskeer je tijd te verliezen!",
    "Hint: mis niet, knijp de kaarten niet met bommen, anders riskeer je de poging te verliezen!",
    "Gewone muziek:",
    "Muziek van de workshop:",
    "Wow! Kijk naar mijn strafblad! kun je dat? Download het klassieke spel: https://play.google.com/store/apps/details?id=com.KJPGames.Classic en probeer om mij heen te komen! Ik weet dat je het niet kunt, maar probeer het, schatje.:)",
    "Verdubbel het geld x2?",
    "Dag",
    "geld",
    "Ontvangen",
    "Dagelijkse bonus",
    "Pak een Cadeau",
    "Verliezen, maar je hebt nog steeds een kans!",
    "Geef het een kans",
    "De dagelijkse bonus wacht op u!",
    "Het is tijd om een nieuw spel te spelen, Kom op we hebben je gemist!",
};
    internal static string[] NameTextsPortuguese =
{
    "Tabela de classificação",
    "Posição",
    "Survive",
    "Nickname",
    "Carregar...",
    "Escolha o modo de jogo",
    "A sobrevivência",
    "BlueShift",
    "Competitivo",
    "Sangramento",
    "A redução спавна bombas durante o jogo",
    "Progresso",
    "O aumento da chance de спавна cartões magnéticos, cartões de tempo de jogo",
    "O aumento спавна dinheiro durante o jogo",
    "Bombear por:",
    "Seu saldo atual:",
    "Teu inventário",
    "Escolha a música que vai começar a jogar",
    "Você também pode escolher a sua própria música:",
    "Em um competitivo modo proibido de jogar com suas músicas!",
    "Conta: ",
    "Dinheiro: ",
    "O combo ",
    "vez consecutiva",
    "Complexidade: ",
    "s ",
    "músicas seguidas!",
    "O resultado do jogo",
    "O teu lugar no ranking:",
    "O total de выжимаемость:",
    "Canções experimentado:",
    "Até que a complexidade alcançado:",
    "Pontos disputado:",
    "O dinheiro levantado:",
    "O máximo de combos por jogo:",
    "Recompensa",
    "Pausa:",
    "Remover anúncios",
    "Você falhou, por 3 vezes consecutivas, no entanto, você pode se livrar de publicidade, apoiando o desenvolvedor e além disso para obter este maravilhoso prêmio:",
    "Digite seu nome",
    "Escolha a sua própria música",
    "Tocando agora: ",
    "A aplicação em pausa saímos...",
    "Erro de conexão com a internet! Por favor conecte seu dispositivo android com a internet e, em seguida, reinicie o jogo...",
    "Preparação de jogos para o lançamento...",
    "A conexão com servidores de K.J.P Games...",
    "Foi detectada uma tentativa de hacking activar a protecção...",
    "Totalmente de melhor!",
    "Transferência de recursos...",
    "Renovação",
    "Uma atualização está disponível para continuar a jogar, instale a sua!",
    "Renovar",
    "Comprar munição para AWP",
    "Alterar configurações de mira",
    "Apenas o cartucho: ",
    "Configurações prazo",
    "Espessura:",
    "É a distância do centro:",
    "Traço:",
    "Vermelho:",
    "A cor azul:",
    "Verde:",
    "T",
    "Poder:",
    "Cartucho: ",
    "Nome: ",
    "Autor: ",
    "Oficina",
    "Adicionar o seu trabalho na oficina",
    "As peles para AWP",
    "Lookahead",
    "Música",
    "O plano de fundo",
    "O tema da AWP",
    "Adicionar o seu trabalho na oficina",
    "Escolha a categoria de adicionar suplementos:",
    "Selecione um arquivo para baixar na oficina:",
    "Selecione o arquivo de ícones para exibir o seu trabalho na oficina",
    "Digite um título para o seu trabalho",
    "Escolher arquivo para o seu dispositivo",
    "Digite um título para o seu trabalho",
    "Carregamento",
    " de ",
    "Velocidade: ",
    "Download concluído",
    "Dica: Прожимай o cartão até o fim, para obter novamente",
    "Dica: Прожимай o cartão até o fim, para ganhar tempo extra",
    "Dica: Use cartões magnéticos, para прожимать vários cartões de uma só vez!",
    "Uma dica: Não промахнись, não прожимай cartão com bombas, caso contrário, corre o risco de perder a hora!",
    "Uma dica: Não промахнись, não прожимай cartão com bombas, caso contrário, corre o risco de perder novamente!",
    "Típica música:",
    "A música do oficina:",
    "Uau! Olhe para o meu recorde!e você é tão consegues? download jogo: https://play.google.com/store/apps/details?id=com.KJPGames.Classic o Clássico E tente contornar a mim! Sei que você não vai sair, mas tente:)",
    "Dobrar o dinheiro x2?",
    "Dia",
    "dinheiro",
    "Obtido",
    "Diário de bônus",
    "Para pegar o presente",
    "Uma perda ,mas você ainda tem uma chance!",
    "Dar a chance de",
    "Diário de bônus já está te esperando!",
    "É hora de jogar de novo, entre nós está com saudades de você!",
};
    internal static string[] NameTextsSwedish =
{
    "Topplista",
    "Position",
    "Squeezability",
    "Smeknamn",
    "Lastning...",
    "Välj spelläge",
    "Överlevnad",
    "BlueShift",
    "Konkurrenskraftig",
    "Pumpande",
    "Minska spawn av bomber under spelet",
    "Framsteg",
    "Öka chansen att leka magnetiska kort under spelet",
    "Öka spawn av pengar under spelet",
    "Pump för:",
    "Ditt nuvarande Saldo:",
    "Ditt lager",
    "Välj den musik du vill börja spela",
    "Du kan också välja din egen musik:",
    "Det är förbjudet att leka med dina egna kompositioner i tävlingsläge!",
    "Konto:",
    "Pengar:",
    "Combo ",
    "en gång i rad",
    "Svårighet:",
    "Överleva ",
    "låtar i rad!",
    "Spel resultat",
    "Din plats i rangordningen:",
    "Totalt squeezability:",
    "Låtar erfarna:",
    "Till vilken grad av komplexitet uppnås:",
    "Poäng vann:",
    "Pengar:",
    "Maximal combo per spel:",
    "Utmärkelser",
    "Paus:",
    "Ta bort annonser",
    "Du har redan förlorat 3 gånger i rad, men du kan bli av med reklam för alltid genom att stödja utvecklaren och utöver detta få denna underbara utmärkelse:",
    "Ange ditt namn",
    "Du kan välja din egen musik",
    "Nu spela: ",
    "Appen pausas för att avsluta..",
    "Fel på internetanslutningen! Anslut din Android-enhet till Internet och starta spelet...",
    "Förbereda spelet för lansering...",
    "Ansluta till servrar K.J.P spel...",
    "Säkerhetsaktiveringen upptäckte ett hackningsförsök...",
    "Helt förbättrad!",
    "Nedladdning av resurser...",
    "Uppdatering",
    "En uppdatering är tillgänglig för att fortsätta spela installera det!",
    "Uppdatering",
    "Köp AWP patroner",
    "Ändra siktar inställningar",
    "Total cylinderampull:",
    "Siktinställningar",
    "Tjocklek:",
    "Avstånd från centrum:",
    "Beskriva:",
    "Röd:",
    "Blå färg:",
    "Grön:",
    "T",
    "Förmåga:",
    "Bläckpatroner: ",
    "Namn:",
    "Författare:",
    "Workshop",
    "Lägg ditt arbete till verkstaden",
    "Skinn för AWP",
    "Förhandsgranskning",
    "Musikalisk",
    "Bakgrund",
    "Hud på AWP",
    "Lägga till ditt eget arbete till verkstaden",
    "Välj kategorin för att lägga till ett tillägg:",
    "Välj en fil att ladda upp till verkstaden:",
    "Välj en ikonfil för att visa ditt arbete i verkstaden",
    "Ange namnet på ditt arbete",
    "Välj en fil på enheten",
    "Ange namnet på ditt arbete",
    "Lastning",
    " från ",
    "Hastighet: ",
    "Nedladdningen är klar",
    "Tips: pressa korten till slutet för att få ett extra försök",
    "Tips: Tryck på korten till slutet för att få extra tid",
    "Tips: Använd magnetiska kort för att pressa flera kort på en gång !",
    "Tips: missa inte, kläm inte korten med bomber, annars riskerar du att förlora tid!",
    "Tips: missa inte, kläm inte korten med bomber, annars riskerar du att förlora försöket!",
    "Vanlig musik:",
    "Musik från verkstaden:",
    "Wow! Titta på min skiva! kan du göra det? Ladda ner det klassiska spelet: https://play.google.com/store/apps/details?id=com.KJPGames.Classic och försök att komma runt mig! Jag vet att du inte kan göra det, men prova det, baby:)",
    "Dubbla pengarna x2?",
    "Dag",
    "pengar",
    "Erhållas",
    "Daglig bonus",
    "Plocka upp en gåva",
    "Förlora, men du har fortfarande en chans!",
    "Ge det en chans",
    "Den dagliga bonusen väntar på dig!",
    "Det är dags att spela ett nytt spel, kom igen vi saknade dig!",
};
internal static string[] NameRewardsRU = 
{ 
        "Дэд Пулл", 
        "Агент Винстон", 
        "Вечерняя заря", 
        "Всквозь любовь", 
        "Въезд в город", 
        "Деренский апокалипсис", 
        "Кибер-панк", 
        "Мантия агресии", 
        "Миленький котёнок", 
        "Парочка из 007", 
        "Пинок в глаз", 
        "Прогулка по району", 
        "Раздумия", 
        "Ты у меня на прицеле", 
        "Улётный особняк", 
        "ЧК", 
        "Денди город", 
        "Мегаполис", 
        "Мешковатое Мерцание", 
        "Оу больше танцев" 
};
    internal static string[] NameRewardsEng =
{
        "Dead Pool",
        "Agent Winston",
        "Sunset",
        "Through and through love",
        "Entrance to city",
        "The traditional Apocalypse",
        "Cyber-punk",
        "The mantle of aggression",
        "Cute kitten",
        "A couple of 007",
        "A kick in the eye",
        "Walking around the area",
        "Thoughts",
        "I have you in my sights",
        "Flyaway mansion",
        "CHK",
        "Dandy city",
        "Megalopolis",
        "Baggy Flicker",
        "Oh more dancing"
};
    internal static string[] NameRewardsFrench =
{
        "Dead Poole",
        "Agent Winston",
        "Crépuscule",
        "À travers l'amour",
        "Entrer dans la ville",
        "L'Apocalypse de Deren",
        "Cyber-punk",
        "Manteau d'agresia",
        "Joli petit chaton",
        "Un couple de 007",
        "Coup de pied dans l'œil",
        "Promenade dans le quartier",
        "Réflexion",
        "Tu es sur ma ligne de mire",
        "Le manoir de l'envol",
        "CHK",
        "Dandy City",
        "Mégalopole",
        "Twinkle Baggy",
        "Ou plus de danse"
};
    internal static string[] NameRewardsItalian =
{
        "Dead Pull",
        "Agente Winston.",
        "Tramonto",
        "Tutto l'amore",
        "Ingresso in città",
        "L'apocalisse di deren",
        "Cyber-punk",
        "Il mantello di agresia",
        "Bel gattino",
        "Una coppia di 007",
        "Un calcio nell'occhio",
        "Passeggiata nel quartiere",
        "Meditazione",
        "Sei nel mio mirino",
        "La villa di lusso",
        "CHK",
        "Città dandy",
        "Metropoli",
        "Luccichio Baggy",
        "Oh, più Danza"
};
    internal static string[] NameRewardsGerman =
{
        "Dead Pull",
        "Agent Winston",
        "Abendröte",
        "Wecke Liebe",
        "Die Einfahrt in die Stadt",
        "Traditionellen Apokalypse",
        "Cyber Punk",
        "Mantel der Aggression",
        "Nettes kleines Kätzchen",
        "Ein paar von 007",
        "Ein Schlag ins Auge",
        "Spaziergang durch die Gegend",
        "Nachdenken",
        "Du bist in meinem Visier",
        "Das fliegende Herrenhaus",
        "CHK",
        "Dandy Stadt",
        "Megapolis",
        "Baggy Flackern",
        "Oh mehr tanzen"
};
    internal static string[] NameRewardsSpanishSpain =
{
        "Dead Pull",
        "Agente Winston",
        "Amanecer de la tarde",
        "El amor",
        "Entrada a la ciudad",
        "Apocalipsis derensky",
        "Cyber punk",
        "Manto de agresión",
        "Lindo gatito",
        "Pareja de 007",
        "Una patada en el ojo",
        "Caminar por el barrio",
        "Reflexiones",
        "Estás a mi alcance",
        "Mansión voladora",
        "CHK",
        "Dandy City",
        "Metrópolis",
        "Brillo Holgado",
        "Oh, más baile"
};
    internal static string[] NameRewardsChina =
{
        "死池",
        "温斯顿探员",
        "日落",
        "通过和通过爱",
        "城市入口",
        "传统的启示录",
        "网络朋克",
        "侵略的斗篷",
        "可爱的小猫",
        "一对夫妇007",
        "在眼睛踢",
        "走在附近",
        "思想",
        "我有你在我的视线",
        "飞航大厦",
        "CHK",
        "花花公子",
        "大都市",
        "宽松的闪烁",
        "哦，更多的舞蹈"
};
    internal static string[] NameRewardsDanish =
{
        "Død Pool",
        "Agent Vinston ",
        "Solnedgang",
        "Gennem og gennem kærlighed",
        "Ind til byen",
        "Den traditionelle apokalypse",
        "Cyber-punk",
        "Aggressionens kappe",
        "Sød killing",
        "Et par 007",
        "Et spark i øjet",
        "Går rundt i området",
        "Tanker",
        "Jeg har dig på kornet",
        "Flyver-palæ",
        "CHK",
        "Dandy city",
        "Megalopolis",
        "Baggy Flimmer",
        "Åh mere Dans"
};
    internal static string[] NameRewardsFinnish =
{
        "Dead Pool",
        "Agentti Winston",
        "Auringonlasku",
        "Läpi rakkauden",
        "Sisäänkäynti kaupunkiin",
        "Perinteinen maailmanloppu",
        "Cyber-punk",
        "Aggression mantteli",
        "Söpö kissanpentu",
        "Pari 007: ää",
        "Potku silmään",
        "Kävelet alueella",
        "Ajatus",
        "Olet tähtäimessäni",
        "Flyawayn kartano",
        "CHK",
        "Dandy city",
        "Megalopolis",
        "Säkki Välkkyy",
        "Lisää tanssia"
};
    internal static string[] NameRewardsNorwegian =
{
        "Dead Svømmebasseng",
        "Agent Winston",
        "Solnedgang",
        "Gjennom og gjennom kjærlighet",
        "Inngangen til byen",
        "Den tradisjonelle Apokalypsen",
        "Cyber-punk",
        "Mantelen av aggresjon",
        "Søt kattunge",
        "Et par av 007",
        "Et spark i øyet",
        "Å vandre rundt i området",
        "Tanke",
        "Jeg har deg i min severdigheter",
        "Flyaway mansion",
        "CHK",
        "Dandy city",
        "Megalopolis",
        "Posete Flimmer",
        "Oh mer dans"
};
    internal static string[] NameRewardsDutch =
{
        "Dead Pool",
        "Agent Winston",
        "Zonsondergang",
        "Door en door liefde",
        "Ingang naar de stad",
        "De traditionele Apocalyps",
        "Cyber-punk",
        "De mantel van agressie",
        "Schattig poesje",
        "Een paar 007",
        "Een schop in het oog",
        "Wandelend door de omgeving",
        "Gedachten",
        "Ik heb je in mijn vizier",
        "Flyaway mansion",
        "CHK",
        "Dandy city",
        "Megapolis",
        "Baggy Flicker",
        "Oh meer dansen"
};
    internal static string[] NameRewardsPortuguese =
{
       "Дэд Пулл",
    "O Agente De Winston",
    "De noite a aurora",
    "Всквозь amor",
    "De entrada na cidade",
    "Деренский apocalipse",
    "Cyber-punk",
    "O manto de агресии",
    "Um gatinho",
    "Casal do 007",
    "Um chute no olho",
    "Um passeio pela zona",
    "Раздумия",
    "Você tem minha visão",
    "Улетный mansão",
    "ЧК",
    "O dandy cidade",
    "Metrópole",
    "Мешковатое Cintilação",
    "Ou mais dança"
};
    internal static string[] NameRewardsSwedish =
{
        "Död Pool",
        "Agent Winston",
        "Solnedgång",
        "Genom och genom kärlek",
        "Ingången till staden",
        "Den traditionella apokalypsen",
        "Cyber-punk",
        "Manteln av aggression",
        "Söt kattunge",
        "Ett par 007",
        "En kick i ögat",
        "Gå runt i området",
        "Tankar",
        "Jag har dig i mina ögon",
        "Flygigt herrgård",
        "SMASK",
        "Dandy city",
        "Megalopolis",
        "Baggy Flimmer",
        "Åh mer dans"
};

}
